POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json

{
  "title": "String",
  "author": "String",
  "url": "String",
  "likes": 100
}

###
GET http://localhost:3003/api/blogs/
