POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZ0ZXN0MiIsImlkIjoiNjJlNmUzMzQzYjY2NmQ5OTdiNjMyZTdlIiwiaWF0IjoxNjU5MzA3NDAyLCJleHAiOjE2NTkzMTEwMDJ9._8sHL_uYIsVlgKFbFFZBm9II2XEEMPonzVWRJ95MpfU

{
  "title": "test15",
  "author": "dangoo",
  "url": "gang5",
  "likes": 2222
}

###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
  "username": "shivtest2",
  "name": "trahahaha",
  "password": "gang4"
}

###
POST http://localhost:3003/api/login HTTP/1.1
content-type: application/json

{
  "username": "shivtest",
  "password": "gang4"
}

###
DELETE http://localhost:3003/api/blogs/62e70bbc2bb0acb1175a3b18 HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZ0ZXN0MiIsImlkIjoiNjJlNmUzMzQzYjY2NmQ5OTdiNjMyZTdlIiwiaWF0IjoxNjU5MzA3NDAyLCJleHAiOjE2NTkzMTEwMDJ9._8sHL_uYIsVlgKFbFFZBm9II2XEEMPonzVWRJ95MpfU

###
GET http://localhost:3003/api/blogs/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoaXZ0ZXN0MiIsImlkIjoiNjJlNmUzMzQzYjY2NmQ5OTdiNjMyZTdlIiwiaWF0IjoxNjU5MzA3NDAyLCJleHAiOjE2NTkzMTEwMDJ9._8sHL_uYIsVlgKFbFFZBm9II2XEEMPonzVWRJ95MpfU